---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: Controller_Node
  become: true
  roles:
    - Neutron
    - Horizon
    - Cinder
